---
title: "STATS 9155B 001 GW20 PROJECT"
author: "Dhanusha Yerubandi"
date: "05/04/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2) 
library(ggrepel)
library(ggthemes) 
library(scales) 
library(dplyr) 
library(VIM)
library(data.table)
library(formattable)
library(plotly)
library(corrplot)
library(GGally)
library(caret)
library(car)
library(stringr)
library(gplots)
library(RColorBrewer)
library(corrplot)
library(nnet)
library(rpart)
library(rpart.plot)
library(MASS)
library(adabag)
library(randomForest)
library(survival)
library(gbm)
library(xgboost)
library(FNN)
library(sjPlot)
library(neuralnet)
library(pROC)
library(multiROC)
```

## Importing dataset
```{r}
movie_reviews <- read.csv("C:/Users/dhanu/OneDrive/Desktop/WINTER 2020/Stats-2/project/Code/movie_metadata.csv")
```

```{r}
str(movie_reviews)
```
```{r}
head(movie_reviews)
```
## Remove Extra character at the end of each movie title

```{r}
movie_reviews$movie_title=as.character(movie_reviews$movie_title)
movie_reviews$movie_title <- gsub("Â", "",movie_reviews$movie_title)
movie_reviews$movie_title=substr(movie_reviews$movie_title,1,nchar(movie_reviews$movie_title)-1)
```

```{r}
#unique(movie_reviews$genres)
```

```{r}
# A new data frame to separate genres
genres.df <- as.data.frame(movie_reviews[,c("genres", "imdb_score")])
genres.df$Action <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Action") 1 else 0)
genres.df$Adventure <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Adventure") 1 else 0)
genres.df$Animation <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Animation") 1 else 0)
genres.df$Biography <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Biography") 1 else 0)
genres.df$Comedy <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Comedy") 1 else 0)
genres.df$Crime <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Crime") 1 else 0)
genres.df$Documentary <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Documentary") 1 else 0)
genres.df$Drama <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Drama") 1 else 0)
genres.df$Family <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Family") 1 else 0)
genres.df$Fantasy <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Fantasy") 1 else 0)
genres.df$`Film-Noir` <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Film-Noir") 1 else 0)
genres.df$History <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "History") 1 else 0)
genres.df$Horror <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Horror") 1 else 0)
genres.df$Musical <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Musical") 1 else 0)
genres.df$Mystery <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Mystery") 1 else 0)
genres.df$News <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "News") 1 else 0)
genres.df$Romance <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Romance") 1 else 0)
genres.df$`Sci-Fi` <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Sci-Fi") 1 else 0)
genres.df$Short <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Short") 1 else 0)
genres.df$Sport <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Sport") 1 else 0)
genres.df$Thriller <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Thriller") 1 else 0)
genres.df$War <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "War") 1 else 0)
genres.df$Western <- sapply(1:length(genres.df$genres), function(x) if (genres.df[x,1] %like% "Western") 1 else 0)
```

```{r}
means <- rep(0,23)
for (i in 1:23) {
  means[i] <- mean(genres.df$imdb_score[genres.df[i+2]==1])
}
# Average score of different genres
barplot(means, main = "Average IMDB score for different genres",xlab = "Different genres",ylab="IMDB score")
```

```{r}
movie_reviews <- subset(movie_reviews, select = -c(genres))
dim(movie_reviews)
```


```{r, include=TRUE, fig.height=10, fig.width= 10}
n_rows = nrow(movie_reviews)
n_cols = ncol(movie_reviews)

na_col = apply(is.na(movie_reviews),2,sum)
na_df = data.frame("key" = colnames(movie_reviews), "count_na" = na_col)
na_df = na_df[with(na_df, order(-count_na)),]

ggplot(na_df, aes(reorder(key,count_na), count_na/5043)) + 
  geom_bar(aes(fill = abs(count_na)/5043 < 0.60),stat='identity') + coord_flip() +
  labs(title = "", x = "Variables",y='Percentage of Missing Values') 
```

```{r}
sum(is.na(movie_reviews$gross))
sum(is.na(movie_reviews$budget))
```
```{r}
movie_reviews <- movie_reviews[!is.na(movie_reviews$gross), ]
movie_reviews <- movie_reviews[!is.na(movie_reviews$budget), ]
dim(movie_reviews)
```
```{r}
sum(complete.cases(movie_reviews))
```
```{r, include=TRUE, fig.height=10, fig.width= 10}
#3891-3801=90 cases still have missing values
na_col = apply(is.na(movie_reviews),2,sum)
na_df = data.frame("key" = colnames(movie_reviews), "count_na" = na_col)
na_df = na_df[with(na_df, order(-count_na)),]

ggplot(na_df, aes(reorder(key,count_na), count_na/3891)) + 
  geom_bar(aes(fill = abs(count_na)/3891 < 0.60),stat='identity') + coord_flip() +
  labs(title = "", x = "Variables",y='Percentage of Missing Values') 
```
```{r}
sum(is.na(movie_reviews$aspect_ratio))
head(movie_reviews$aspect_ratio)
tail(movie_reviews$aspect_ratio)
```

```{r}
movie_reviews$aspect_ratio[is.na(movie_reviews$aspect_ratio)] <- 0
mean(movie_reviews$imdb_score[movie_reviews$aspect_ratio == 1.85])
mean(movie_reviews$imdb_score[movie_reviews$aspect_ratio == 2.35])
mean(movie_reviews$imdb_score[movie_reviews$aspect_ratio != 1.85 & movie_reviews$aspect_ratio != 2.35])
```
```{r}
# no big difference in mean between three aspect_ratios
# remove aspect_ratio feature
movie_reviews <- subset(movie_reviews, select = -c(aspect_ratio))
dim(movie_reviews)
```


```{r}
# Reamaining columns with null entries are of type integer, therefore, NA can be replaced with column mean
movie_reviews[,c(5,6,8,13,24,26)][movie_reviews[,c(5,6,8,13,24,26)] == 0] <- NA

movie_reviews$actor_3_facebook_likes[is.na(movie_reviews$actor_3_facebook_likes)] <- round(mean(movie_reviews$actor_3_facebook_likes, na.rm = TRUE))

movie_reviews$facenumber_in_poster[is.na(movie_reviews$facenumber_in_poster)] <- round(mean(movie_reviews$facenumber_in_poster, na.rm = TRUE))

movie_reviews$actor_2_facebook_likes[is.na(movie_reviews$actor_2_facebook_likes)] <- round(mean(movie_reviews$actor_2_facebook_likes, na.rm = TRUE))

movie_reviews$actor_1_facebook_likes[is.na(movie_reviews$actor_1_facebook_likes)] <- round(mean(movie_reviews$actor_1_facebook_likes, na.rm = TRUE))

movie_reviews$num_critic_for_reviews[is.na(movie_reviews$num_critic_for_reviews)] <- round(mean(movie_reviews$num_critic_for_reviews, na.rm = TRUE))

movie_reviews$duration[is.na(movie_reviews$duration)] <- round(mean(movie_reviews$duration, na.rm = TRUE))
```

```{r, include=TRUE, fig.height=10, fig.width= 10}
na_col = apply(is.na(movie_reviews),2,sum)
na_df = data.frame("key" = colnames(movie_reviews), "count_na" = na_col)
na_df = na_df[with(na_df, order(-count_na)),]

ggplot(na_df, aes(reorder(key,count_na), count_na/3891)) + 
  geom_bar(aes(fill = abs(count_na)/3891 < 0.60),stat='identity') + coord_flip() +
  labs(title = "", x = "Variables",y='Percentage of Missing Values') 
```

```{r}
sum(is.na(movie_reviews$movie_facebook_likes))
```
```{r}
movie_reviews$movie_facebook_likes[is.na(movie_reviews$movie_facebook_likes)] <- round(mean(movie_reviews$movie_facebook_likes, na.rm = TRUE))

movie_reviews$director_facebook_likes[is.na(movie_reviews$director_facebook_likes)] <- round(mean(movie_reviews$director_facebook_likes, na.rm = TRUE))

movie_reviews$cast_total_facebook_likes[is.na(movie_reviews$cast_total_facebook_likes)] <- round(mean(movie_reviews$cast_total_facebook_likes, na.rm = TRUE))

```

```{r, include=TRUE, fig.height=10, fig.width= 10}
na_col = apply(is.na(movie_reviews),2,sum)
na_df = data.frame("key" = colnames(movie_reviews), "count_na" = na_col)
na_df = na_df[with(na_df, order(-count_na)),]

ggplot(na_df, aes(reorder(key,count_na), count_na/3891)) + 
  geom_bar(aes(fill = abs(count_na)/3891 < 0.60),stat='identity') + coord_flip() +
  labs(title = "", x = "Variables",y='Percentage of Missing Values') 
```

```{r}
movie_reviews <- movie_reviews[!(movie_reviews$content_rating %in% ""),]

movie_reviews$content_rating[movie_reviews$content_rating == 'M']   <- 'PG' 
movie_reviews$content_rating[movie_reviews$content_rating == 'GP']  <- 'PG' 
movie_reviews$content_rating[movie_reviews$content_rating == 'X']   <- 'NC-17'

movie_reviews$content_rating[movie_reviews$content_rating == 'Approved']  <- 'R' 
movie_reviews$content_rating[movie_reviews$content_rating == 'Not Rated'] <- 'R' 
movie_reviews$content_rating[movie_reviews$content_rating == 'Passed']    <- 'R' 
movie_reviews$content_rating[movie_reviews$content_rating == 'Unrated']   <- 'R'

movie_reviews$content_rating = as.factor(movie_reviews$content_rating)

```




```{r}
table(movie_reviews$content_rating)
```
```{r}
movie_reviews$budget=as.numeric(movie_reviews$budget)
movie_reviews$gross=as.numeric(movie_reviews$gross)
movie_reviews <- movie_reviews %>% mutate(profit_value = abs(gross - budget),ROI_percent = abs( (profit_value/budget) )*100)
head(movie_reviews$profit_value)
head(movie_reviews$ROI_percent)
```
```{r}
unique(movie_reviews$color)
ggplot(movie_reviews, aes(color)) +
  geom_bar(aes(fill=color))
```



```{r}
movie_reviews <- subset(movie_reviews, select = -c(color))
dim(movie_reviews)
```
```{r, include=TRUE, fig.height=10, fig.width= 20}
unique(movie_reviews$language)
ggplot(movie_reviews,aes(language))+geom_bar(aes(fill=language))
```

```{r}
movie_reviews <- subset(movie_reviews, select = -c(language))
dim(movie_reviews)
```
```{r, include=TRUE, fig.height=15, fig.width= 30}
unique(movie_reviews$country)
ggplot(movie_reviews,aes(country))+geom_bar(aes(fill=country))
```

```{r}
levels(movie_reviews$country) <- c(levels(movie_reviews$country), "Others")
movie_reviews$country[(movie_reviews$country != 'USA')&(movie_reviews$country != 'UK')] <- 'Others' 
movie_reviews$country <- factor(movie_reviews$country)
table(movie_reviews$country)
ggplot(movie_reviews,aes(country))+geom_bar(aes(fill=country))
```

```{r,include=TRUE, fig.height=10, fig.width= 20}
ggplot(movie_reviews, aes(title_year)) +
  geom_bar(color="blue") +
  labs(x = "Movie release years", y = "Movie Count", title = "Histogram of number of movie releases in a year") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
movie_reviews <- movie_reviews[movie_reviews$title_year >= 1975,]
```

```{r, include=TRUE, fig.height=15, fig.width= 20}
movie_reviews %>%
  filter(title_year %in% c(1980:2016)) %>%
  arrange(desc(profit_value)) %>%
  top_n(20, profit_value) %>%
  ggplot(aes(x=budget/1000000, y=profit_value/1000000)) +
  geom_point() +
  geom_smooth() + 
  geom_text_repel(aes(label=movie_title)) +
  labs(x = "Budget $million", y = "Profit $million", title = "Top 20 Profitable Movies") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
ggplot(aes(x=imdb_score, y=profit_value/1000000), data=movie_reviews) +
    geom_line() + stat_smooth(color='blue',span=1)
```

```{r, include=TRUE, fig.height=10, fig.width= 15}
movie_reviews %>%
  filter(budget > 100000) %>%
  arrange(desc(profit_value)) %>%
  top_n(20, profit_value) %>%
  ggplot(aes(x=budget/1000000, y = ROI_percent)) + 
  geom_point(size = 2) + 
  geom_smooth(size = 1) + 
  geom_text_repel(aes(label = movie_title), size = 3) + 
  xlab("Budget $million") + 
  ylab("Percent Return on Investment") + 
  ggtitle("20 Most Profitable Movies based on its Return on Investment")
```

```{r}
ggplot(movie_reviews,aes(x=country,y=imdb_score)) +
    geom_point() 
```


```{r}
ggplot(movie_reviews,aes(x = movie_facebook_likes, y = imdb_score))+geom_point(aes(color=movie_reviews$content_rating),alpha=0.5)
```

```{r, include=TRUE, fig.height=10, fig.width= 25}
movie_reviews %>%
  arrange(desc(imdb_score)) %>% top_n(20, imdb_score) %>% ggplot(aes(x = director_name, y = imdb_score))+geom_point(aes(color=movie_title),alpha=3)
```

```{r, include=TRUE, fig.height=10, fig.width= 20}
movie_reviews %>%
  top_n(20, profit_value) %>%
  ggplot(aes(x = imdb_score, y = gross/10^6, size = profit_value/10^6, color = content_rating)) + 
  geom_point() + 
  geom_hline(aes(yintercept = 600)) + 
  geom_vline(aes(xintercept = 7.75)) + 
  geom_text_repel(aes(label = movie_title), size = 4) +
  xlab("Imdb score") + 
  ylab("Gross money earned in million dollars") + 
  ggtitle("Commercial success Vs Critical acclaim") +
  annotate("text", x = 8.5, y = 700, label = "High ratings \n & High gross") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r, include=TRUE, fig.height=10, fig.width= 20}
movie_reviews %>%
  arrange(desc(imdb_score)) %>% top_n(20, imdb_score) %>% ggplot(aes(x = country, y = imdb_score))+geom_point(aes(color=movie_title),alpha=3)
```

```{r, include=TRUE, fig.height=10, fig.width= 28}
movie_reviews %>%
  arrange(desc(imdb_score)) %>% top_n(20, imdb_score) %>% ggplot(aes(x = actor_1_name, y = imdb_score))+geom_point(aes(color=movie_title),alpha=3)
```


```{r, include=TRUE, fig.height=10, fig.width= 28}
movie_reviews %>%
  arrange(desc(imdb_score)) %>% top_n(20, imdb_score) %>% ggplot(aes(x = actor_2_name, y = imdb_score))+geom_point(aes(color=movie_title),alpha=3)
```


```{r, include=TRUE, fig.height=10, fig.width= 28}
movie_reviews %>%
  arrange(desc(imdb_score)) %>% top_n(20, imdb_score) %>% ggplot(aes(x = actor_3_name, y = imdb_score))+geom_point(aes(color=movie_title),alpha=3)
```

```{r, include=TRUE, fig.height=10, fig.width= 20}
movie_reviews %>%
  arrange(desc(imdb_score)) %>% top_n(20, imdb_score) %>% ggplot(aes(x = actor_1_facebook_likes, y = imdb_score))+geom_point(aes(color=movie_title),alpha=3)
```
```{r}
movie_reviews <- subset(movie_reviews, select = -c(director_name, actor_2_name, actor_1_name,movie_title, actor_3_name,movie_imdb_link))
```

```{r}
movie_reviews <- subset(movie_reviews,select=-c(plot_keywords))
```

```{r}
sum(duplicated(movie_reviews))
```

```{r}
movie_reviews <- movie_reviews[!duplicated(movie_reviews), ]
```

```{r}
dim(movie_reviews)
```

```{r}
movie_reviews <- subset(movie_reviews, select = -c(profit_value,ROI_percent))
```

```{r}
ggcorr(movie_reviews, label = TRUE, label_round = 2, label_size = 3.5, size = 2, hjust = .85) +
  ggtitle("Correlation Heatmap") +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
movie_reviews$tot_other_actors_facebook_likes <- movie_reviews$actor_2_facebook_likes + movie_reviews$actor_3_facebook_likes
```

```{r}
movie_reviews <- subset(movie_reviews, select = -c(actor_2_facebook_likes,actor_3_facebook_likes))
```

```{r}
movie_reviews <- subset(movie_reviews, select = -c(cast_total_facebook_likes))
```

```{r}
movie_reviews$critic_review_user_ratio <- movie_reviews$num_critic_for_reviews / movie_reviews$num_user_for_reviews
```

```{r}
movie_reviews <- subset(movie_reviews, select = -c(num_critic_for_reviews,num_user_for_reviews))
```

```{r}
ggcorr(movie_reviews, label = TRUE, label_round = 2, label_size = 3.5, size = 2, hjust = .85) +
  ggtitle("Correlation Heatmap") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
dim(movie_reviews)
```

```{r}
colnames(movie_reviews)
```

```{r}
movie_reviews$class_imdb_score <- cut(movie_reviews$imdb_score, breaks = c(0,3,5,7,10))
```

```{r}

# Set seed and create assignment
set.seed(1)
assignment <- sample(1:3, size = nrow(movie_reviews), prob = c(.70,.15,.15), replace = TRUE)

# Create a train, validation and tests from the original data frame 
imdb_train <- movie_reviews[assignment == 1, ]    # subset movie_reviews to training indices only
imdb_valid <- movie_reviews[assignment == 2, ]  # subset movie_reviews to validation indices only
imdb_test <- movie_reviews[assignment == 3, ]   # subset movie_reviews to test indices only
```

```{r}
dec_tree <- rpart(class_imdb_score ~ . -imdb_score, data = imdb_train, method = "class")
prp(dec_tree, type = 1, extra = 1, under = TRUE, split.font = 2, varlen = 0) 
```

```{r}
set.seed(1)
cv_tree <- rpart(class_imdb_score ~ . -imdb_score, data = imdb_train, method = "class", 
               cp = 0.00001, minsplit = 5, xval = 5)
printcp(cv_tree)
```

```{r}
prune_cv_tree <- prune(cv_tree, 
                   cp = cv_tree$cptable[which.min(cv_tree$cptable[,"xerror"]),"CP"])
length(prune_cv_tree$frame$var[prune_cv_tree$frame$var == "<leaf>"])

prp(prune_cv_tree, type = 1, extra = 1, split.font = 1, varlen = -10)
```

```{r}
# apply model on training set
train_pred_tree <- predict(prune_cv_tree, imdb_train, type = "class")
# generate confusion matrix for training data
confusionMatrix(train_pred_tree, imdb_train$class_imdb_score)

```
```{r}
# apply model on training set
valid_pred_tree <- predict(prune_cv_tree, imdb_valid, type = "class")
# generate confusion matrix for training data
confusionMatrix(valid_pred_tree, imdb_valid$class_imdb_score)
```

```{r}
# apply model on training set
test_pred_tree <- predict(prune_cv_tree, imdb_test, type = "class")
# generate confusion matrix for training data
confusionMatrix(test_pred_tree, imdb_test$class_imdb_score)
```
```{r}
varImp(prune_cv_tree)
```


```{r}
#str(movie_reviews)
set.seed(53)
ran_forest <- randomForest(class_imdb_score ~ . -imdb_score, data = imdb_train, mtry = 5)
```

```{r}
valid_rf <- predict(ran_forest,imdb_valid)
confusionMatrix(valid_rf, imdb_valid$class_imdb_score)
```
```{r}
test_rf <- predict(ran_forest,imdb_test)
confusionMatrix(test_rf, imdb_test$class_imdb_score)
```

```{r}
plot(ran_forest)
legend('topright', colnames(ran_forest$err.rate), col=1:5, fill=1:5)
```

```{r}
imp <- importance(ran_forest)
featureImportance <- data.frame(Feature=row.names(imp), Importance=imp[,1])

p <- ggplot(featureImportance, aes(x=reorder(Feature, Importance), y=Importance)) +
     geom_bar(stat="identity", fill="#53cfff") +
     coord_flip() + 
     theme_light(base_size=20) +
     xlab("") +
     ylab("Importance") + 
     ggtitle("Random Forest Feature Importance\n") +
     theme(plot.title=element_text(size=18))
```

```{r,fig.width=15}
p
```


```{r}
movie_bagging=bagging(class_imdb_score ~ . -imdb_score, data = imdb_train,nbagg=60,coob=TRUE)
```

```{r}
importanceplot(movie_bagging)
```


```{r}
valid_bagg=predict.bagging(movie_bagging,imdb_valid)
valid_bagg$confusion
valid_bagg$error
```
```{r}
test_bagg=predict.bagging(movie_bagging,imdb_test)
test_bagg$confusion
test_bagg$error
```


```{r}
Boston.boost=boosting(class_imdb_score ~ .-imdb_score ,data = imdb_train,n.trees = 10000,
                  shrinkage = 0.09, interaction.depth = 5)
#Boston.boost

summary(Boston.boost) #Summary gives a table of Variable Importance and a plot of Variable Importance
```

```{r}
importanceplot(Boston.boost)
```



```{r}
valid_gradient=predict.boosting(Boston.boost,imdb_valid,n.trees = 10000)
valid_gradient$confusion
valid_gradient$error
```

```{r}
test_gradient=predict.boosting(Boston.boost,imdb_test,n.trees = 10000)
test_gradient$confusion
test_gradient$error
```

```{r}
movie_reviews2 <- movie_reviews
```

```{r}
movie_reviews2$country <- as.factor(movie_reviews2$country)
movie_reviews2$content_rating <- as.factor(movie_reviews2$content_rating)
movie_reviews2[,c("UK", "USA", "Others")] <- model.matrix( ~ country - 1, data = movie_reviews2)
movie_reviews2[,c("G", "NC17", "PG", "PG13", "R")] <- model.matrix( ~ content_rating - 1, data = movie_reviews2)
```
```{r}
movie_reviews2 <- movie_reviews2[, c(1,2,3,4,5,6,7,8,9,10,11,16,17,18,19,20,21,22,23,15)]
```


```{r}
set.seed(123)
imdb_train2 <- movie_reviews2[assignment == 1, ]    # subset movie_reviews to training indices only
imdb_valid2 <- movie_reviews2[assignment == 2, ]  # subset movie_reviews to validation indices only
imdb_test2 <- movie_reviews2[assignment == 3, ]   # subset movie_reviews to test indices only
```

```{r}
norm_train2=imdb_train2
norm_valid2=imdb_valid2
norm_test2=imdb_test2
norm_movie_reviews2 = movie_reviews2
norm_values=preProcess(imdb_train2,method=c("center","scale"))
norm_train2<- predict(norm_values, imdb_train2)
norm_valid2 <- predict(norm_values, imdb_valid2)
norm_test2 <- predict(norm_values, imdb_test2)
norm_movie_reviews2 <- predict(norm_values, movie_reviews2)
```
```{r}
set.seed(123)
model <- train(
  class_imdb_score ~.-imdb_score, data = norm_train2, method = "knn",
  trControl = trainControl("cv", number = 10),
  tuneLength = 20
  )
# Plot model accuracy vs different values of k
plot(model)
```

```{r}
model$bestTune
```
```{r}
predicted.classes_valid <- model %>% predict(norm_valid2)
head(predicted.classes_valid)
```
```{r}
mean(predicted.classes_valid == norm_valid2$class_imdb_score)
```


```{r}
predicted.classes <- model %>% predict(norm_test2)
head(predicted.classes)
```
```{r}
mean(predicted.classes == norm_test2$class_imdb_score)
```

```{r}
str(movie_reviews2)
```


```{r}
nn <- nnet(class_imdb_score~num_voted_users+title_year+duration+director_facebook_likes+actor_1_facebook_likes+gross+facenumber_in_poster+budget+UK+USA+Others+G+NC17+PG+PG13+R,data=norm_train2,size=5,linear.output = FALSE,threshold=0.01)
```

```{r,fig.height=15,fig.width=15}
summary(nn)
```

```{r}
temp_valid <- subset(norm_valid2, select = c("num_voted_users","title_year","duration","director_facebook_likes","actor_1_facebook_likes","gross","facenumber_in_poster","budget","UK","USA","Others","G","NC17","PG","PG13","R"))
head(temp_valid)
nn.results_valid <- predict(nn, temp_valid,type="class")
```


```{r}
cm1 <- table(nn.results_valid,norm_valid2$class_imdb_score)
cm1
```



```{r}
#Test the resulting output
temp_test <- subset(norm_test2, select = c("num_voted_users","title_year","duration","director_facebook_likes","actor_1_facebook_likes","gross","facenumber_in_poster","budget","UK","USA","Others","G","NC17","PG","PG13","R"))
head(temp_test)
nn.results_test <- predict(nn, temp_test,type="class")
 
```

```{r}
cm2 <- table(nn.results_test,norm_test2$class_imdb_score)
cm2
```
```{r}
set.seed(53)
ran_forest2 <- randomForest(class_imdb_score ~ . -imdb_score-country-facenumber_in_poster-content_rating, data = imdb_train, mtry = 5)
```

```{r}
valid_rf2 <- predict(ran_forest2,imdb_valid)
confusionMatrix(valid_rf2, imdb_valid$class_imdb_score)
```

```{r}
test_rf2 <- predict(ran_forest2,imdb_test)
confusionMatrix(test_rf2, imdb_test$class_imdb_score)
```

```{r}
set.seed(53)
ran_forest3 <- randomForest(class_imdb_score ~ num_voted_users+duration+budget+critic_review_user_ratio+gross, data = imdb_train,mtry=5)
```

```{r}
valid_rf3 <- predict(ran_forest3,imdb_valid)
confusionMatrix(valid_rf3, imdb_valid$class_imdb_score)
```

```{r}
test_rf3 <- predict(ran_forest3,imdb_test)
confusionMatrix(test_rf3, imdb_test$class_imdb_score)
```

